In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data.csv')

In [3]:
df.head()

fever  BodyPain  age  RunnyNose  diffBreath  infectionProb
0   98.221377         1   67          1           0              1
1   98.368929         0   28          0           0              0
2   98.242217         1   54          1           1              1
3  100.560316         1   18          1          -1              1
4   99.547369         1   55          0           1              1

In [4]:
df.tail()

fever  BodyPain  age  RunnyNose  diffBreath  infectionProb
2994   98.879899         1   82          0          -1              1
2995   98.937803         1   79          1           1              0
2996  101.182390         0   43          0           1              0
2997  101.816072         1   89          0           1              0
2998   99.635195         1   34          1           1              0

In [5]:
df.isnull().sum()

fever            0
BodyPain         0
age              0
RunnyNose        0
diffBreath       0
infectionProb    0
dtype: int64

In [6]:
df.describe()

fever     BodyPain          age    RunnyNose   diffBreath  \
count  2999.000000  2999.000000  2999.000000  2999.000000  2999.000000   
mean     99.990214     0.501834    49.985328     0.515839    -0.004001   
std       1.149811     0.500080    29.082967     0.499832     0.817983   
min      98.001113     0.000000     1.000000     0.000000    -1.000000   
25%      98.997029     0.000000    25.000000     0.000000    -1.000000   
50%      99.996787     1.000000    49.000000     1.000000     0.000000   
75%     100.947581     1.000000    76.000000     1.000000     1.000000   
max     101.999468     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2999.000000  
mean        0.512504  
std         0.499927  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 6 columns):
fever            2999 non-null float64
BodyPain         2999 non-null int64
age              2999 non-null int64
RunnyNose        2999 non-null int64
diffBreath       2999 non-null int64
infectionProb    2999 non-null int64
dtypes: float64(1), int64(5)
memory usage: 140.7 KB


In [8]:
df['diffBreath'].value_counts()

-1    1009
 1     997
 0     993
Name: diffBreath, dtype: int64

In [9]:
import numpy as np

In [10]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]
    

In [11]:
train,test = data_split(df,0.2)

In [12]:
train

fever  BodyPain  age  RunnyNose  diffBreath  infectionProb
1103  101.847928         0   44          1          -1              1
1569   98.225690         0   80          1           0              0
2229   98.417071         1    5          0           1              1
2296  101.904343         0    3          0          -1              0
1800   98.225701         1   51          1           1              0
...          ...       ...  ...        ...         ...            ...
1638   98.612467         1   49          0          -1              1
1095   99.524270         0   81          1          -1              1
1130  101.495864         0   18          1           1              0
1294   99.317518         1   63          1           0              0
860   101.249324         1   69          0           0              0

[2400 rows x 6 columns]

In [13]:
np.shape(train)

(2400, 6)

In [14]:
test

fever  BodyPain  age  RunnyNose  diffBreath  infectionProb
1376   99.050134         0    8          1          -1              0
932   100.026744         1   45          1           0              0
144    99.215622         0   73          0          -1              0
1752   98.518907         1   30          0          -1              0
51     99.973939         0   38          0           0              1
...          ...       ...  ...        ...         ...            ...
842    98.304963         0   91          0          -1              0
637    98.237025         1   56          0          -1              1
695    98.901269         1   52          0          -1              1
226    98.979437         0   82          1           0              1
2603   98.509753         1   40          0           0              0

[599 rows x 6 columns]

In [15]:
X_train = train[['fever','BodyPain','age','RunnyNose','diffBreath']].to_numpy()
X_test =test[['fever','BodyPain','age','RunnyNose','diffBreath']].to_numpy()

In [16]:
X_test

array([[ 99.05013387,   0.        ,   8.        ,   1.        ,
         -1.        ],
       [100.0267441 ,   1.        ,  45.        ,   1.        ,
          0.        ],
       [ 99.21562173,   0.        ,  73.        ,   0.        ,
         -1.        ],
       ...,
       [ 98.90126883,   1.        ,  52.        ,   0.        ,
         -1.        ],
       [ 98.97943662,   0.        ,  82.        ,   1.        ,
          0.        ],
       [ 98.50975338,   1.        ,  40.        ,   0.        ,
          0.        ]])

In [17]:
Y_train = train[['infectionProb']].to_numpy().reshape(2400,)

In [18]:
Y_test = test[['infectionProb']].to_numpy().reshape(599,)

In [19]:
Y_train

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [20]:
Y_test

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,

In [21]:
np.size(Y_test)

599

In [22]:
from sklearn.linear_model import LogisticRegression


In [23]:
clf = LogisticRegression(solver='lbfgs')
clf.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [38]:
inputFeatures = [100.45,1,64,1,-1]
infoProb = clf.predict_proba([inputFeatures])[0][1]

In [39]:
print("The Probability of covid is:",str(infoProb*100)+"%")

The Probability of covid is: 52.14763851163037%
